name: Публикация книги
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3
    - name: Установка mdbook
      run: |
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Сборка книги
      run: mdbook build
    - name: Публикация книги
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book
